fragment LayoutQueryFragment on Query {
  global(relativePath: "index.json") {
    ...GlobalParts
  }
}

fragment MediaQueryFragment on Query {
  mediaManager(relativePath: "index.json") {
    ...MediaManagerParts
  }
}
